language: cpp
dist: bionic

compiler:
  - clang

before_script:
  - mkdir -p .build_release
  - cd .build_release
  - cmake ..

before_install:
  - pip install --user cpp-coveralls

script:
  - make
  - make test

after_success:
  - coveralls --root . -E ".*CMakeFiles.*" 