language: cpp
os: linux

#env:
#    global:
#        - LLVM_VERSION=8.0.0

matrix:
  include:
    - os: linux
    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
          packages: ['clang++-8', 'lcov', 'zlib1g-dev', 'llvm-8-dev']
      env: COMPILER=clang++-8


before_script:
  - mkdir -p .build_release
  - cd .build_release
  - cmake -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ZLIB=ON ..

script:
  - make

  - llvm-cov-8 export --version
  - LLVM_PROFILE_FILE=./run_tests.profraw ./run_tests
  - llvm-profdata merge ./run_tests.profraw -o ./run_tests.profdata
  - llvm-cov-8 export -format=lcov -instr-profile ./run_tests.profdata ./run_tests  > cov.info
  - genhtml cov.info --output-directory out
  - bash <(curl -s https://codecov.io/bash) -f cov.info || echo "Codecov did not collect coverage reports"
