language: cpp
os: linux

compiler: clang

env:
  - LLVM_VERSION=8.0.0
  - CC=clang-8
  - CXX=clang++-8
  - CXXSTD=-std=c++17

addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-xenial-8']
    packages: ['clang++-8', 'lcov', 'zlib1g-dev', 'llvm-8-dev']

before_script:
  - mkdir -p .build_release
  - cd .build_release
  - cmake ..

script:
  - make

  - llvm-cov export --version
  - LLVM_PROFILE_FILE=./run_tests.profraw ./run_tests
  - llvm-profdata merge run_tests.profraw -o run_tests.profdata
  - llvm-cov export -format=lcov -instr-profile run_tests.profdata ./run_tests  > cov.info
  - genhtml cov.info --output-directory out
  - bash <(curl -s https://codecov.io/bash) -f cov.info || echo "Codecov did not collect coverage reports"
