language: cpp
dist: bionic

 - os: linux
      name: "Xenial - clang 9"
      dist: xenial
      env: [USE_CC='/usr/bin/clang-9', USE_CXX='/usr/bin/clang++-9']
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages: ['clang-9', 'cmake', 'libstdc++-9-dev', 'libstdc++6']

compiler:
  - clang

addons:
  apt:
    packages: lcov
    packages: llvm

before_script:
  - mkdir -p .build_release
  - cd .build_release
  - cmake ..

script:
  - make

  - llvm-cov export --version
  - LLVM_PROFILE_FILE=./run_tests.profraw ./run_tests
  - llvm-profdata merge run_tests.profraw -o run_tests.profdata
  - llvm-cov export -format=lcov -instr-profile run_tests.profdata ./run_tests  > cov.info
  - genhtml cov.info --output-directory out
  - bash <(curl -s https://codecov.io/bash) -f cov.info || echo "Codecov did not collect coverage reports"
